Models/Line.cs
using System.ComponentModel.DataAnnotations.Schema;
using System.ComponentModel.DataAnnotations;

namespace projekt.Models
{
    [Table("Lines")]
    public class Line
    {
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int Id { get; set; }

        [Required]
        [StringLength(50)]
        [Display(Name = "Nazwa linii")]
        public string? Name { get; set; }    /*nazwa linii*/

        [Required]
        [StringLength(10)]
        [Display(Name = "Skrót")]
        public string? Shortcut { get; set; }

        public virtual ICollection<Flight>? Flights { get; set; }

        public virtual ICollection<LinePlane>? LinePlanes { get; set; }
    }
}

Controllers/LinePlanesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using projekt.Data;
using projekt.Models;

namespace projekt.Controllers
{
    public class LinePlanesController : Controller
    {
        private readonly projektContext _context;

        public LinePlanesController(projektContext context)
        {
            _context = context;
        }

        // GET: LinePlanes
        public async Task<IActionResult> Index()
        {
            var projektContext = _context.LinePlane.Include(l => l.Line).Include(l => l.Plane);
            return View(await projektContext.ToListAsync());
        }

        // GET: LinePlanes/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.LinePlane == null)
            {
                return NotFound();
            }

            var linePlane = await _context.LinePlane
                .Include(l => l.Line)
                .Include(l => l.Plane)
                .FirstOrDefaultAsync(m => m.LinePlaneID == id);
            if (linePlane == null)
            {
                return NotFound();
            }

            return View(linePlane);
        }

        // GET: LinePlanes/Create
        public IActionResult Create()
        {
            ViewData["LineId"] = new SelectList(_context.Line, "Id", "Name");
            ViewData["PlaneId"] = new SelectList(_context.Set<Plane>(), "Id", "Model");
            return View();
        }

        // POST: LinePlanes/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("LinePlaneID,LineId,PlaneId")] LinePlane linePlane)
        {
            if (ModelState.IsValid)
            {
                _context.Add(linePlane);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["LineId"] = new SelectList(_context.Line, "Id", "Name", linePlane.LineId);
            ViewData["PlaneId"] = new SelectList(_context.Set<Plane>(), "Id", "Model", linePlane.PlaneId);
            return View(linePlane);
        }

        // GET: LinePlanes/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.LinePlane == null)
            {
                return NotFound();
            }

            var linePlane = await _context.LinePlane.FindAsync(id);
            if (linePlane == null)
            {
                return NotFound();
            }
            ViewData["LineId"] = new SelectList(_context.Line, "Id", "Name", linePlane.LineId);
            ViewData["PlaneId"] = new SelectList(_context.Set<Plane>(), "Id", "Model", linePlane.PlaneId);
            return View(linePlane);
        }

        // POST: LinePlanes/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("LinePlaneID,LineId,PlaneId")] LinePlane linePlane)
        {
            if (id != linePlane.LinePlaneID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(linePlane);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!LinePlaneExists(linePlane.LinePlaneID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["LineId"] = new SelectList(_context.Line, "Id", "Name", linePlane.LineId);
            ViewData["PlaneId"] = new SelectList(_context.Set<Plane>(), "Id", "Model", linePlane.PlaneId);
            return View(linePlane);
        }

        // GET: LinePlanes/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.LinePlane == null)
            {
                return NotFound();
            }

            var linePlane = await _context.LinePlane
                .Include(l => l.Line)
                .Include(l => l.Plane)
                .FirstOrDefaultAsync(m => m.LinePlaneID == id);
            if (linePlane == null)
            {
                return NotFound();
            }

            return View(linePlane);
        }

        // POST: LinePlanes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.LinePlane == null)
            {
                return Problem("Entity set 'projektContext.LinePlane'  is null.");
            }
            var linePlane = await _context.LinePlane.FindAsync(id);
            if (linePlane != null)
            {
                _context.LinePlane.Remove(linePlane);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool LinePlaneExists(int id)
        {
          return (_context.LinePlane?.Any(e => e.LinePlaneID == id)).GetValueOrDefault();
        }
    }
}

Controllers/LinesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using projekt.Data;
using projekt.Models;

namespace projekt.Controllers
{
    public class LinesController : Controller
    {
        private readonly projektContext _context;

        public LinesController(projektContext context)
        {
            _context = context;
        }

        // GET: Lines
        public async Task<IActionResult> Index()
        {
              return _context.Line != null ? 
                          View(await _context.Line.ToListAsync()) :
                          Problem("Entity set 'projektContext.Line'  is null.");
        }

        // GET: Lines/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Line == null)
            {
                return NotFound();
            }

            var line = await _context.Line
                .Include(f => f.LinePlanes)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (line == null)
            {
                return NotFound();
            }

            return View(line);
        }

        // GET: Lines/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Lines/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Name,Shortcut")] Line line)
        {
            if (ModelState.IsValid)
            {
                _context.Add(line);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(line);
        }

        // GET: Lines/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Line == null)
            {
                return NotFound();
            }

            var line = await _context.Line.FindAsync(id);
            if (line == null)
            {
                return NotFound();
            }
            return View(line);
        }

        // POST: Lines/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name,Shortcut")] Line line)
        {
            if (id != line.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(line);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!LineExists(line.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(line);
        }

        // GET: Lines/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Line == null)
            {
                return NotFound();
            }

            var line = await _context.Line
                .FirstOrDefaultAsync(m => m.Id == id);
            if (line == null)
            {
                return NotFound();
            }

            return View(line);
        }

        // POST: Lines/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Line == null)
            {
                return Problem("Entity set 'projektContext.Line'  is null.");
            }
            var line = await _context.Line.FindAsync(id);
            if (line != null)
            {
                _context.Line.Remove(line);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool LineExists(int id)
        {
          return (_context.Line?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

Views/Lines/Create.cshtml
@model projekt.Models.Line

@{
    ViewData["Title"] = "Create";
}

<h2>Create</h2>

<h4 class="mt-1">Line</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Shortcut" class="control-label"></label>
                <input asp-for="Shortcut" class="form-control" />
                <span asp-validation-for="Shortcut" class="text-danger"></span>
            </div>
            <div class="form-group mt-3">
                <input type="submit" value="Create" class="btn1" />
            </div>
        </form>
    </div>
</div>

<div class="mt-3">
    <a class="btn1" asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Lines/Delete.cshtml
@model projekt.Models.Line

@{
    ViewData["Title"] = "Delete";
}

<h2>Delete</h2>

<h3 class="mt-1">Are you sure you want to delete this?</h3>
<div>
    <h4>Line</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Shortcut)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Shortcut)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn2" /> |
        <a class="btn1 mt-3" asp-action="Index">Back to List</a>
    </form>
</div>

Views/Lines/Details.cshtml
@model projekt.Models.Line

@{
    ViewData["Title"] = "Details";
}

<h2>Details</h2>

<div class="mt-1">
    <h4>Line</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Shortcut)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Shortcut)
        </dd>
        <dt class="col-sm-2">
            Flota
        </dt>
        <dd class="col-sm-10">
            @if (Model.LinePlanes != null && Model.LinePlanes.Any())
            {
                <ul>
                    @foreach (var plane in Model.LinePlanes)
                    {
                        <li>@plane.PlaneId</li>
                    }
                </ul>
            }
            else
            {
                <p>This line does not have planes assigned.</p>
            }
        </dd>
    </dl>
</div>
<div>
    <a class="btn1" asp-action="Edit" asp-route-id="@Model?.Id">Edit</a> |
    <a class="btn1" asp-action="Index">Back to List</a>
</div>

Views/Lines/Edit.cshtml
@model projekt.Models.Line

@{
    ViewData["Title"] = "Edit";
}

<h2>Edit</h2>

<h4 class="mt-1">Line</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Shortcut" class="control-label"></label>
                <input asp-for="Shortcut" class="form-control" />
                <span asp-validation-for="Shortcut" class="text-danger"></span>
            </div>
            <div class="form-group  mt-3">
                <input type="submit" value="Save" class="btn1" />
            </div>
        </form>
    </div>
</div>

<div class="mt-3">
    <a class="btn1" asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Lines/Index.cshtml
@model IEnumerable<projekt.Models.Line>

@{
    ViewData["Title"] = "Index";
}

<h2>Index</h2>

<p>
    <a class="btn1" asp-action="Create">Create New</a>
    <a class="btn1" asp-action="Index" asp-controller="LinePlanes">Manage Planes</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Shortcut)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Shortcut)
            </td>
            <td>
                    <a class="btn1" asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                    <a class="btn1" asp-action="Details" asp-route-id="@item.Id">Details</a> |
                    <a class="btn1" asp-action="Delete" asp-route-id="@item.Id">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>